{"name": "test_add", "status": "failed", "statusDetails": {"message": "AssertionError: the expected data is : 20 and we got :10\nassert 10 == 20", "trace": "@allure.severity(allure.severity_level.NORMAL)\n    @allure.epic('Back-End Test')\n    @allure.feature('ADD')\n    @allure.story('check the add function')\n    def test_add():\n        with allure.step(\"check 2 parameters :\" + str(add_two) + \" and :\" + str(\n                add_one) + \" the expected rez is: \" + str(add_expected_pass)):\n            actual = beck_end_func.add(add_one, add_two)\n            assert actual == add_expected_pass, \"the expected data is : \" + str(add_expected_pass) + \" and we got :\" + str(\n                actual)\n    \n        with allure.step(\"check 2 parameters :\" + str(add_two) + \" and :\" + str(\n                add_one) + \" the expected rez is: \" + str(add_expected_pass)):\n            actual = beck_end_func.add(add_one, add_two)\n            assert actual == add_expected_pass, \"the expected data is : \" + str(add_expected_pass) + \" and we got :\" + str(\n                actual)\n    \n        with allure.step(\"check 2 parameters :\" + str(add_two) + \" and :\" + str(\n                add_one) + \" the expected rez is: \" + str(add_expected_fail)):\n            actual = beck_end_func.add(add_one, add_two)\n>           assert actual == add_expected_fail, \"the expected data is : \" + str(add_expected_fail) + \" and we got :\" + str(\n                actual)\nE           AssertionError: the expected data is : 20 and we got :10\nE           assert 10 == 20\n\nTests\\test_me.py:80: AssertionError"}, "steps": [{"name": "check 2 parameters :5 and :5 the expected rez is: 10", "status": "passed", "start": 1534848229692, "stop": 1534848229692}, {"name": "check 2 parameters :5 and :5 the expected rez is: 10", "status": "passed", "start": 1534848229692, "stop": 1534848229692}, {"name": "check 2 parameters :5 and :5 the expected rez is: 20", "status": "failed", "statusDetails": {"message": "AssertionError: the expected data is : 20 and we got :10\nassert 10 == 20\n", "trace": "  File \"D:\\python\\FinalReport\\Tests\\test_me.py\", line 80, in test_add\n    assert actual == add_expected_fail, \"the expected data is : \" + str(add_expected_fail) + \" and we got :\" + str(\n"}, "start": 1534848229692, "stop": 1534848229692}], "start": 1534848229692, "stop": 1534848229692, "uuid": "28fd0e91-30b2-42f9-b8fa-a412be8e3a33", "historyId": "8f9a05509f10882ceb812e7959c8e14d", "fullName": "Tests.test_me#test_add", "labels": [{"name": "story", "value": "check the add function"}, {"name": "feature", "value": "ADD"}, {"name": "epic", "value": "Back-End Test"}, {"name": "severity", "value": "normal"}, {"name": "host", "value": "L-T-HAIMSHP-WW"}, {"name": "thread", "value": "30728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_me"}]}