{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: the expected data is : 20 and we got :0\nassert 0 == 20", "trace": "@allure.severity(allure.severity_level.CRITICAL)\n    @allure.epic('Back-End Test')\n    @allure.feature('SUB')\n    @allure.story('check the sub function')\n    def test_sub():\n        with allure.step(\"check 2 parameters :\" + str(add_two) + \" and :\" + str(\n                add_one) + \" the expected rez is: \" + str(sub_expected_pass)):\n            actual = beck_end_func.sub(add_one, add_two)\n            assert actual == sub_expected_pass, \"the expected data is : \" + str(sub_expected_pass) + \" and we got :\" + str(\n                actual)\n    \n        with allure.step(\"check 2 parameters :\" + str(add_two) + \" and :\" + str(\n                add_one) + \" the expected rez is: \" + str(sub_expected_pass)):\n            actual = beck_end_func.sub(add_one, add_two)\n            assert actual == sub_expected_pass, \"the expected data is : \" + str(sub_expected_pass) + \" and we got :\" + str(\n                actual)\n    \n        with allure.step(\"check 2 parameters :\" + str(add_two) + \" and :\" + str(\n                add_one) + \" the expected rez is: \" + str(add_expected_fail)):\n            actual = beck_end_func.sub(add_one, add_two)\n>           assert actual == add_expected_fail, \"the expected data is : \" + str(add_expected_fail) + \" and we got :\" + str(\n                actual)\nE           AssertionError: the expected data is : 20 and we got :0\nE           assert 0 == 20\n\nTests\\test_me.py:104: AssertionError"}, "steps": [{"name": "check 2 parameters :5 and :5 the expected rez is: 0", "status": "passed", "start": 1534848229708, "stop": 1534848229708}, {"name": "check 2 parameters :5 and :5 the expected rez is: 0", "status": "passed", "start": 1534848229708, "stop": 1534848229708}, {"name": "check 2 parameters :5 and :5 the expected rez is: 20", "status": "failed", "statusDetails": {"message": "AssertionError: the expected data is : 20 and we got :0\nassert 0 == 20\n", "trace": "  File \"D:\\python\\FinalReport\\Tests\\test_me.py\", line 104, in test_sub\n    assert actual == add_expected_fail, \"the expected data is : \" + str(add_expected_fail) + \" and we got :\" + str(\n"}, "start": 1534848229708, "stop": 1534848229708}], "start": 1534848229708, "stop": 1534848229708, "uuid": "7171cb60-8348-4df8-9793-b310356983d0", "historyId": "4821b5468f5288d321a56e403a30880f", "fullName": "Tests.test_me#test_sub", "labels": [{"name": "story", "value": "check the sub function"}, {"name": "feature", "value": "SUB"}, {"name": "epic", "value": "Back-End Test"}, {"name": "severity", "value": "critical"}, {"name": "host", "value": "L-T-HAIMSHP-WW"}, {"name": "thread", "value": "30728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_me"}]}